# Generated by Django 4.1.2 on 2022-10-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scent', models.CharField(max_length=75)),
                ('color', models.CharField(max_length=75)),
                ('ounces', models.IntegerField()),
                ('burn_time', models.IntegerField()),
            ],
        ),
    ]
