# Generated by Django 4.1.2 on 2022-10-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='burning date')),
                ('duration', models.IntegerField()),
                ('room', models.CharField(choices=[('L', 'Living Room'), ('B', 'Bedroom'), ('D', 'Dining Room')], default='L', max_length=1)),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.candle')),
            ],
        ),
    ]
