# Generated by Django 4.1.2 on 2022-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_burning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enjoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='burning',
            options={'ordering': ['-date']},
        ),
    ]
