# Generated by Django 4.1.2 on 2022-10-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_enjoyer_alter_burning_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='enjoyers',
            field=models.ManyToManyField(to='main_app.enjoyer'),
        ),
    ]
